[package]
name = "urbi4"
version = "0.1.0"
authors = ["Matthieu Nottale <matthieu@nottale.net>"]

[dependencies]
pest = "^1.0.0-beta"
pest_derive = "^1.0.0-beta"
lazy_static = "1.0.0"
maplit = "1.0.1"
cpython = "0.1.0"

[[bin]]
name = "urbi4"
path = "src/main.rs"
